services:
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - family-planner-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=family_planner
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: backend:latest
    build:
      context: backend
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"

volumes:
  family-planner-db-data: